### ISSUE TITLE
Car speed can be adjusted remotely

### ISSUE THREAD

**Issue by ZJW-92** [DIT112-V20/group-08#10]
### User story
As a user driving the car, I want to be able to adjust the speed of the car according to meditation level, so that I can control the speed on my own will. 

### Acceptable critera
The speed of the car shall be adjustable remotely, and the speed that the car can reach will change with meditation level from a percentage between 0-100.

**Comment by livmari** [comment]
This issue has been in "to do" in the project board for a while. What is the status of it?

**Comment by ZJW-92** [comment]
We can just move the car when meditation value changes, but still work on on which way can make the car accelerate.
