### ISSUE TITLE
Improved steering for manual control

### ISSUE THREAD

**Issue by matekd** [DIT112-V20/group-08#118]
### User story
As a driver I want to be able to steer the car while it is still and when it is moving to driving more versatile.

### Acceptance criteria
The car can turn while driving forward and when it is stationary.

Expanding the apps manual controller to use the latest driving and steering features in the car.

**Comment by livmari** [comment]
@matekd , should this be added to #117 ? It looks like @ZJW-92 had time to solve it there. :)
