### ISSUE TITLE
Wifi connection between app and smart car

### ISSUE THREAD

**Issue by AnnanLao** [DIT112-V20/group-08#12]
### Use story
As a user, I want to be able to connect to the smart car via wifi, so that I can drive my car with a remote control app.

### Acceptance criteria
The car can be controlled by the android app via a wifi connection.

**Comment by livmari** [comment]
This issue is a part of the app front end milestone, but isn't it more back-end related?

**Comment by livmari** [comment]
I'm closing this issue because we put wifi connection on ice :)
