### ISSUE TITLE
Port detection doesn't work on macOS Catalina

### ISSUE THREAD

**Issue by AnnanLao** [DIT112-V20/group-08#20]
Describe the bug
It is not possible to upload code to the boards because Port Detection doesn't work.
No Port is shown in the board manager. I tried with Nano Every and Uno, no luck.

OS macOS Catalina (MacBook Pro 15'' 2018)

**Comment by platisd** [comment]
Have you tried downloading the [drivers](https://www.silabs.com/products/development-tools/software/usb-to-uart-bridge-vcp-drivers)?

**Comment by AnnanLao** [comment]
Thank you for your immediate response--it saves my day.
