### ISSUE TITLE
 Connectivity issue when car switches from reverse to forward and vice versa

### ISSUE THREAD

**Issue by dojodj** [DIT112-V20/group-08#41]
At the moment the car is being controlled via bluetooth. Whenever we order the car to change the car.setSpeed() value from 50 to -50 the car drives backwards for a few seconds then connection is lost. We are assuming the cause to this issue is because of the gap between 50 and -50 is to great and causes some unhandled errors that crashes the blueetooth connection. 

Solution 1
We should try to figure out the threshold for the car and then increase the gap gradually from there. 
Solution 2
Set up a WiFi server and connect through that, hopefully the connection is more stable.

**Comment by platisd** [comment]
> Set up a WiFi server and connect through that, hopefully the connection is more stable.

That's not very likely. :)

Another solution is to have a small delay between the movements.
