### ISSUE TITLE
Partial/complete control of mind backend and connection

### ISSUE THREAD

**Issue by AnnanLao** [DIT112-V20/group-08#58]

**Comment by AnnanLao** [comment]
As a user, I want to completely control the car with my mind to have it driven with only my mind.
As a user, I want to partially control the car with my mind to have it driven with 50% my mind and 50% the manual control

**Comment by livmari** [comment]
I was already working on this in sprint2. It's about to be merged with the branch pull request I just made. Could you review it maybe? :)

Clarification: It's a part of a functioning activity_main.xml file, and was already a documented issue, but the code was lost due to a merge error.
