### ISSUE TITLE
The controlEeg button does not switch back to default state when "stop" is clicked

### ISSUE THREAD

**Issue by livmari** [DIT112-V20/group-08#67]
### User story
As an end-user, I want to be able to toggle EEG concentration readings on and off, so that I can have the application correspond with me wearing/not wearing the headset.

### Acceptance criteria / bug explanation
This is a bug that came about when the start stop buttons were merged into a single button that should switch state instead.

Whenever the "start" button is pressed it turns from green to red, and changes the text to "stop".
The issue is that it doesn't work in reverse for some reason. The button doesn't turn from "stop" to "start" and red to green.

**Comment by livmari** [comment]
@AnnanLao could you help me with this issue after merging back to master? :)

**Comment by AnnanLao** [comment]
> @AnnanLao could you help me with this issue after merging back to master? :)

Sure
