### ISSUE TITLE
Car cannot be controlled by the headset with the latest code

### ISSUE THREAD

**Issue by matekd** [DIT112-V20/group-08#70]
The file smartcar.ino makes the car only accept contiguous input to move, however when paired with headset the movement becomes choppy and unusable.

**Comment by dojodj** [comment]
One solution could be to have two separate  methods for handling inputs, one for the headset and one for manual control. I also think we can make some improvements for the manual control if we decide to spend time on that aspect, like using joystick or something to have a wider variety of control of the vehicle.
